name: GitHub Actions React Build
'on':
  push:
    branches:
      - master
jobs:
  React_build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install and Build
        run: |
          npm install
          npm run-script build
      - name: Set up SSH key for EC2 access
        uses: aws/ssh -i key.pem ubuntu@65.1.111.237
        with:
          ssh-private-key: '${{ secrets.EC2_SSH_PRIVATE_KEY }}'
      - name: Transfer build files to EC2
        run: >
          scp -r ./build/* ssh -i key.pem ubuntu@65.1.111.237{{
          secrets.EC2_PUBLIC_IP }}:/var/www/html/
        env:
          SSH_PRIVATE_KEY: '${{ secrets.EC2_SSH_PRIVATE_KEY }}'
          EC2_PUBLIC_IP: '${{ secrets.EC2_PUBLIC_IP }}'
